const actions = {
  //modal actions
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  //User Actions
  CREATE_USER: "CREATE_USER",
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
  PURGE_CURRENT_USER: 'PURGE_CURRENT_USER'
};
export default actions;
