const actions = {
  //modal actions
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  //User Actions
  CREATE_USER: "CREATE_USER",
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
  PURGE_CURRENT_USER: 'PURGE_CURRENT_USER',
  //Battletag
  CREATE_BATTLETAG_SUCCESS: 'CREATE_BATTLETAG_SUCCESS',
  CREATE_BATTLETAG_FAILURE: 'CREATE_BATTLETAG_FAILURE',
  //Select Battletag
  SELECT_BATTLETAG_SUCCESS: 'SELECT_BATTLETAG_SUCCESS',
  SELECT_BATTLETAG_FAILURE: 'SELECT_BATTLETAG_FAILURE',
  //Season Form
  //SEASON FORM
  NEXT_STEP_SEASON_FORM: "NEXT_STEP_SEASON_FORM",
  SET_STARTING_SR: "SET_STARTING_SR",
  SET_HEROS_FOCUSED: "SET_HEROS_FOCUSED",
  RESET_SEASON_FORM: "RESET_SEASON_FORM",
  //SEASON ACTIONS
  SAVE_SEASON_SUCCESS: "SAVE_SEASON_SUCCESS",
  SAVE_SEASON_FAILURE: "SAVE_SEASON_FAILURE",
  //Delete Battletag
  DELETE_BATTLETAG_SUCCESS: 'DELETE_BATTLETAG_SUCCESS',
  DELETE_BATTLETAG_FAILURE: 'DELETE_BATTLETAG_FAILURE',
};
export default actions;
